# Generated by Django 5.2 on 2025-11-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64)),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('ai_answer', models.TextField(blank=True)),
                ('forwarded_to_professor', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('INTENT', 'Intent created'), ('TEXT_SUBMITTED', 'Text submitted & cleaned'), ('AI_ANSWERED', 'AI answered'), ('FORWARDED', 'Forwarded to professor')], default='INTENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.session')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('MANUAL', 'Professor marked important'), ('QUESTION', 'Question with capture'), ('HARD', 'Hard threshold capture')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('screenshot_image', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecture.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.session')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64)),
                ('feedback_type', models.CharField(choices=[('OK', 'OK'), ('HARD', 'HARD')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('course', 'date'), name='uniq_session_per_course_per_date'),
        ),
    ]
