# Generated by Django 5.2 on 2025-11-15 14:56

import lecture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_load_subjectinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantmoment',
            name='screenshot_image',
            field=models.ImageField(blank=True, null=True, upload_to=lecture.models.important_moment_screenshot_upload_path),
        ),
    ]
