# Generated by Django 5.2 on 2025-11-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_questionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantmoment',
            name='is_hardest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='hardest_moments_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
