# Generated by Django 5.2 on 2025-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_importantmoment_is_hardest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='professor_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('INTENT', 'Intent created'), ('TEXT_SUBMITTED', 'Text submitted & cleaned'), ('AI_ANSWERED', 'AI answered'), ('FORWARDED', 'Forwarded to professor'), ('PROFESSOR_ANSWERED', 'Professor answered')], default='INTENT', max_length=20),
        ),
    ]
