# Generated by Django 5.2 on 2025-11-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_question_professor_answer_alter_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='professor_answer',
        ),
    ]
