"""
Django settings for inthon7 project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from google.oauth2 import service_account
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 로드 (프로젝트 루트 기준)
# - 로컬 개발에서는 GCS_CREDENTIALS_FILE 등 환경변수를 .env에서 읽어오고
# - 배포 환경에서는 OS 환경변수를 그대로 사용
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(w$dlfg1(j6c5*qkz1nioy)9oi$har$be!j%od$h8g*ppczvrm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'channels',
    'storages',
    'lecture',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inthon7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inthon7.wsgi.application'
ASGI_APPLICATION = 'inthon7.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    }
}

GS_BUCKET_NAME = "inthon7-bucket"

# 서비스 계정 키 경로를 환경변수(.env)에서 가져와 설정
# - 기본: GCS_CREDENTIALS_FILE
# - 혹은 표준 GOOGLE_APPLICATION_CREDENTIALS 사용
GCS_CREDENTIAL_FILE = (
    os.environ.get("GCS_CREDENTIALS_FILE")
    or os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
)

GS_CREDENTIALS = None
if GCS_CREDENTIAL_FILE:
    try:
        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
            GCS_CREDENTIAL_FILE
        )
    except Exception as e:
        # dev 환경에서 경로가 잘못돼도 전체 서버가 죽지 않도록 하고,
        # GCS 라이브러리의 기본 credential 검색 로직에 맡긴다.
        print(f"[WARN] Failed to load GCS credentials from {GCS_CREDENTIAL_FILE}: {e}")

# Django 5 방식의 STORAGES 설정 (기본 파일 저장소를 GCS로 설정)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {
            "bucket_name": GS_BUCKET_NAME,
            **({"credentials": GS_CREDENTIALS} if GS_CREDENTIALS else {}),
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 업로드된 미디어 파일 URL (GCS 공개 버킷 기준)
MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"

# 새로 업로드되는 객체를 공개 읽기 권한으로 만들고,
# URL에 서명 쿼리스트링을 붙이지 않도록 설정
GS_QUERYSTRING_AUTH = False

# Django REST framework / OpenAPI 설정
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "InThon API",
    "DESCRIPTION": "API documentation for InThon lecture service",
    "VERSION": "1.0.0",
}